# Install firefox
addons:
  firefox: latest
  chrome: stable

language: dart
sudo: required

dart:
  - stable
  - beta
  - dev
before_script:
  - cd repo_support
  - dart pub get
  - # Set firefox headless
  - export MOZ_HEADLESS=1
script:
  - dart tool/travis.dart
# matrix:
#  allow_failures:
#    - dart: dev