name: sembast_repo
description: Sembast repo
version: 0.1.0
homepage: https://github.com/tekartik/sembast.dart
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.4.0-dev <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.0+1'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'


