name: sembast
version: 3.7.3+1
description: NoSQL persistent embedded file system document-based database for Dart VM and Flutter with encryption support.
homepage: https://github.com/tekartik/sembast.dart/tree/master/sembast
topics:
  - nosql
  - database

funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: ^3.5.0

dependencies:
  meta: ">=1.3.0 <3.0.0"
  path: ">=1.8.0 <3.0.0"
  synchronized: ">=3.0.0 <5.0.0"

dev_dependencies:
  lints: ">=4.0.0"
  http: ">=1.2.2"
  test: ">=1.25.8"
  process_run: '>=1.1.0'
  build_runner: ">=2.4.2"
  build_web_compilers: ">=4.0.11"
  build_test: ">=2.2.0"
  # Tool
  yaml: '>=3.1.2'
  pub_semver: ">=2.1.4"
