name: sembast
version: 3.0.0-nullsafety.0
description: NoSQL persistent embedded file system document-based database for Dart VM and Flutter with encryption support.
homepage: https://github.com/tekartik/sembast.dart/tree/master/sembast

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: '>=1.3.0-nullsafety.6 <3.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  synchronized: '>=3.0.0-nullsafety.1 <5.0.0'
  pedantic: '>=1.10.0-nullsafety.3 <3.0.0'
dev_dependencies:
  http: '>=0.11.0'
  test: '>=1.16.0-nullsafety.11'
  process_run: '>=0.10.2'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
  # Tool
  io:
  yaml:
  pub_semver:
  # Dependencies for encryption example
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'
