name: sembast_web
description: NoSQL persistent embedded database for the Web on top of IndexedDB
version: 2.1.0+4
homepage: https://github.com/tekartik/sembast.dart/tree/master/sembast_web

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  sembast: '>=3.4.2-1 <5.0.0'
  idb_shim: '>=2.3.0+2 <4.0.0'
  synchronized: '>=3.0.1 <5.0.0'
dev_dependencies:
  lints: '>=1.0.1'
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  build_runner: '>=1.11.3'
  build_test: '>=1.3.7'
  build_web_compilers: '>=2.16.4'
