name: sembast_test
description: Test helpers for sembast and sembast_web
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.6.0
  sembast:
  sembast_web:
  test:
  # Dependencies for encryption example
  encrypt: '>=5.0.0-0'
  crypto: '>=3.0.0'
  pedantic:

dev_dependencies:
  http: '>=0.11.0'
  process_run: '>=0.12.0'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
  test_core:
  meta: '>=1.2.0'
  # Tool
  io:
  yaml:
  pub_semver:

dependency_overrides:
  # pedantic: '>=1.9.0'
  sembast:
    path: ../sembast
  sembast_web:
    path: ../sembast_web
