name: sembast_test
description: Test helpers for sembast and sembast_web
version: 0.3.1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  path: '>=1.6.0'
  sembast: '>=3.4.3-3'
  sembast_web: '>=2.4.4-1'
  test:
  collection:
  # Dependencies for encryption example
  encrypt: '>=5.0.0-0'
  crypto: '>=3.0.0'

dev_dependencies:
  idb_shim: '>=2.7.1+2'
  lints: '>=1.0.1'
  http: '>=0.11.0'
  process_run: '>=0.12.0'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
  test_core:
  meta: '>=1.2.0'
  # Tool
  io:
  yaml:
  pub_semver:

dependency_overrides:
  sembast:
    path: ../sembast
  sembast_web:
    path: ../sembast_web
