name: sembast_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.5.0

dependencies:
  process_run: '>=0.10.0'

dev_dependencies:
  test: '>=1.0.0'
  dev_build: '>=0.16.4+2'
  lints: '>=1.0.1'
  path:
dependency_overrides:
  # dev_build:
  #   path: ../../dev_test.dart/dev_build
